### ISSUE TITLE
Remove « placement »

### ISSUE THREAD

**Issue by gjuchault** [ungdev/arena.utt.fr-2015#3]
What will be done instead of automatic placement :

Print two A4 :
- One with the list of all teams and its position on the map
- One with the simplified plan

When the first member of a team arrives; he chooses where him and his team is placed. The staff adds to the first A4 the name; and color on the plan the place (to mark it « taken »)
When another member of the same team arrives, the staff tells him where his team is

**Comment by hugocollignon** [comment]
Or write the team name on the map
Le 29 août 2015 18:58, "Gabriel JUCHAULT" notifications@github.com a
écrit :

**Comment by gjuchault** [comment]
That would maybe take too much place

**Comment by ghost** [comment]
And the issue is closed, the map will be done by hand the day of the event (as wanted by Alexis and @Exalyon).
